// src/visualizer.ts — HTML report generator for codebase intelligence visualization.
// Produces a self-contained HTML file with module dependency graph, co-change clusters,
// execution flows, blast radius explorer, and project stats.
// Zero runtime dependencies — Mermaid loaded via CDN for graph rendering only.

import type { StructuredAnalysis } from "./types.js";

/**
 * Generate a self-contained HTML report from a StructuredAnalysis.
 * Returns a complete HTML document string.
 */
export function generateReport(analysis: StructuredAnalysis): string {
  const pkg = analysis.packages[0];
  if (!pkg) return "<html><body><p>No packages found in analysis.</p></body></html>";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(pkg.name)} — Codebase Intelligence Report</title>
${renderStyles()}
</head>
<body>
<div class="container">
  ${renderHeader(pkg)}
  ${renderDependencyGraph(pkg)}
  ${renderClusters(pkg)}
  ${renderFlows(pkg)}
  ${renderBlastRadius(pkg)}
  ${renderConventions(pkg)}
  <footer>
    <p>Generated by <strong>autodocs-engine</strong> v${analysis.meta.engineVersion} &mdash; ${analysis.meta.analyzedAt.slice(0, 10)}</p>
  </footer>
</div>
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true, theme: 'neutral', securityLevel: 'loose' });
</script>
${renderBlastRadiusScript(pkg)}
</body>
</html>`;
}

// ─── Styles ──────────────────────────────────────────────────────────────────

function renderStyles(): string {
  return `<style>
  :root { --bg: #fafafa; --card: #fff; --border: #e0e0e0; --accent: #2563eb; --text: #1a1a1a; --muted: #666; }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #111; --card: #1a1a1a; --border: #333; --accent: #60a5fa; --text: #e5e5e5; --muted: #999; }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }
  .container { max-width: 1100px; margin: 0 auto; padding: 2rem 1.5rem; }
  h1 { font-size: 1.8rem; margin-bottom: 0.25rem; }
  h2 { font-size: 1.3rem; margin: 2.5rem 0 1rem; border-bottom: 2px solid var(--accent); padding-bottom: 0.3rem; }
  .subtitle { color: var(--muted); font-size: 0.95rem; margin-bottom: 2rem; }
  .stats { display: flex; flex-wrap: wrap; gap: 1rem; margin: 1.5rem 0; }
  .stat { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem 1.25rem; min-width: 140px; }
  .stat-value { font-size: 1.5rem; font-weight: 700; color: var(--accent); }
  .stat-label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; margin: 0.75rem 0; }
  .cluster-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
  .cluster-card { background: var(--card); border-left: 4px solid var(--accent); border-radius: 0 8px 8px 0; padding: 1rem; border-top: 1px solid var(--border); border-right: 1px solid var(--border); border-bottom: 1px solid var(--border); }
  .cluster-card:nth-child(2) { border-left-color: #10b981; }
  .cluster-card:nth-child(3) { border-left-color: #f59e0b; }
  .cluster-card:nth-child(4) { border-left-color: #ef4444; }
  .cluster-card:nth-child(5) { border-left-color: #8b5cf6; }
  .cluster-title { font-weight: 600; margin-bottom: 0.5rem; }
  .cluster-files { font-size: 0.85rem; color: var(--muted); }
  .cluster-files code { background: var(--bg); padding: 0.1rem 0.3rem; border-radius: 3px; font-size: 0.8rem; }
  .flow { display: flex; align-items: center; flex-wrap: wrap; gap: 0.25rem; margin: 0.5rem 0; font-size: 0.85rem; }
  .flow-step { background: var(--card); border: 1px solid var(--border); padding: 0.3rem 0.6rem; border-radius: 4px; white-space: nowrap; }
  .flow-arrow { color: var(--muted); }
  .flow-conf { margin-left: 0.5rem; font-size: 0.75rem; padding: 0.15rem 0.5rem; border-radius: 10px; }
  .conf-high { background: #dcfce7; color: #166534; }
  .conf-med { background: #fef3c7; color: #92400e; }
  .conf-low { background: #f3f4f6; color: #6b7280; }
  select { font-size: 0.95rem; padding: 0.4rem 0.8rem; border: 1px solid var(--border); border-radius: 6px; background: var(--card); color: var(--text); }
  .blast-results { margin-top: 1rem; }
  .blast-section { margin: 0.75rem 0; }
  .blast-section h4 { font-size: 0.85rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.3rem; }
  .blast-section ul { list-style: none; padding: 0; }
  .blast-section li { font-size: 0.85rem; padding: 0.2rem 0; }
  .blast-section li code { background: var(--bg); padding: 0.1rem 0.3rem; border-radius: 3px; }
  .badge { display: inline-block; font-size: 0.7rem; padding: 0.1rem 0.4rem; border-radius: 3px; margin-left: 0.3rem; }
  .badge-import { background: #dbeafe; color: #1e40af; }
  .badge-cochange { background: #fef3c7; color: #92400e; }
  .badge-implicit { background: #fce7f3; color: #9d174d; }
  .convention-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 0.5rem; }
  .convention-item { font-size: 0.85rem; padding: 0.5rem 0.75rem; background: var(--card); border: 1px solid var(--border); border-radius: 6px; }
  .convention-do { border-left: 3px solid #10b981; }
  .convention-dont { border-left: 3px solid #ef4444; }
  .mermaid { margin: 1rem 0; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.8rem; text-align: center; }
  .empty { color: var(--muted); font-style: italic; font-size: 0.9rem; }
</style>`;
}

// ─── Header + Stats ──────────────────────────────────────────────────────────

function renderHeader(pkg: StructuredAnalysis["packages"][0]): string {
  const stats = [
    { value: pkg.files.total, label: "Files" },
    { value: pkg.publicAPI.length, label: "Public API" },
    { value: pkg.callGraph?.length ?? 0, label: "Call Graph Edges" },
    { value: pkg.importChain?.length ?? 0, label: "Import Edges" },
    { value: pkg.gitHistory?.coChangeEdges?.length ?? 0, label: "Co-change Pairs" },
    { value: pkg.coChangeClusters?.length ?? 0, label: "Clusters" },
    { value: pkg.executionFlows?.length ?? 0, label: "Execution Flows" },
    { value: pkg.conventions?.length ?? 0, label: "Conventions" },
  ];

  return `
  <h1>${esc(pkg.name)}</h1>
  <p class="subtitle">${esc(pkg.role.summary || pkg.description || "")} &mdash; ${pkg.architecture.packageType}</p>
  <div class="stats">
    ${stats.map((s) => `<div class="stat"><div class="stat-value">${s.value}</div><div class="stat-label">${s.label}</div></div>`).join("\n    ")}
  </div>`;
}

// ─── Module Dependency Graph ─────────────────────────────────────────────────

function renderDependencyGraph(pkg: StructuredAnalysis["packages"][0]): string {
  const edges = pkg.importChain ?? [];
  if (edges.length === 0) return "";

  // Aggregate to directory level
  const dirEdges = new Map<string, number>();
  for (const e of edges) {
    const from = fileDir(e.importer);
    const to = fileDir(e.source);
    if (from === to) continue;
    const key = `${from}|${to}`;
    dirEdges.set(key, (dirEdges.get(key) ?? 0) + e.symbolCount);
  }

  if (dirEdges.size === 0) return "";

  // Build Mermaid graph
  const mermaidLines = ["graph LR"];
  for (const [key, count] of [...dirEdges.entries()].sort((a, b) => b[1] - a[1]).slice(0, 25)) {
    const [from, to] = key.split("|");
    const fromId = mermaidId(from);
    const toId = mermaidId(to);
    const thickness = count >= 20 ? "==>" : count >= 5 ? "-->" : "-.->";
    mermaidLines.push(`  ${fromId}["${esc(from)}/"] ${thickness}|${count}| ${toId}["${esc(to)}/"]`);
  }

  return `
  <h2>Module Dependencies</h2>
  <div class="card">
    <pre class="mermaid">${mermaidLines.join("\n")}</pre>
  </div>`;
}

// ─── Co-Change Clusters ──────────────────────────────────────────────────────

function renderClusters(pkg: StructuredAnalysis["packages"][0]): string {
  const clusters = pkg.coChangeClusters ?? [];
  const implicit = pkg.implicitCoupling ?? [];

  if (clusters.length === 0 && implicit.length === 0) return "";

  const cards: string[] = [];

  for (let i = 0; i < clusters.length; i++) {
    const c = clusters[i];
    const fileList = c.map((f) => `<code>${esc(shortPath(f))}</code>`).join("<br>");
    cards.push(`
      <div class="cluster-card">
        <div class="cluster-title">Cluster ${i + 1} &mdash; ${c.length} files</div>
        <div class="cluster-files">${fileList}</div>
      </div>`);
  }

  let implicitHtml = "";
  if (implicit.length > 0) {
    const items = implicit
      .slice(0, 8)
      .map(
        (e) =>
          `<li><code>${esc(shortPath(e.file1))}</code> &harr; <code>${esc(shortPath(e.file2))}</code> <span class="badge badge-implicit">${Math.round(e.jaccard * 100)}% co-change, no import</span></li>`,
      )
      .join("\n");
    implicitHtml = `
    <h3 style="font-size:1rem;margin:1.5rem 0 0.5rem;color:var(--muted)">Implicit Coupling (no import relationship)</h3>
    <ul style="list-style:none;padding:0;font-size:0.85rem">${items}</ul>`;
  }

  return `
  <h2>Co-Change Clusters</h2>
  <p style="color:var(--muted);font-size:0.9rem;margin-bottom:1rem">Files that frequently change together in commits. Each cluster is a group where every pair co-changes.</p>
  <div class="cluster-grid">${cards.join("\n")}</div>
  ${implicitHtml}`;
}

// ─── Execution Flows ─────────────────────────────────────────────────────────

function renderFlows(pkg: StructuredAnalysis["packages"][0]): string {
  const flows = pkg.executionFlows ?? [];
  if (flows.length === 0) return "";

  const flowHtml = flows.slice(0, 7).map((f) => {
    const steps = f.steps
      .map((s, i) => {
        const file = f.files[i] ? ` title="${esc(f.files[i])}"` : "";
        return `<span class="flow-step"${file}>${esc(s)}</span>`;
      })
      .join('<span class="flow-arrow">&rarr;</span>');

    const confClass = f.confidence >= 0.3 ? "conf-high" : f.confidence >= 0.1 ? "conf-med" : "conf-low";
    const confLabel = f.confidence > 0 ? `${Math.round(f.confidence * 100)}%` : "structural";

    return `<div class="flow">${steps}<span class="flow-conf ${confClass}">${confLabel}</span></div>`;
  });

  return `
  <h2>Execution Flows</h2>
  <p style="color:var(--muted);font-size:0.9rem;margin-bottom:1rem">Detected execution paths through the call graph. Confidence scored by git co-change history.</p>
  <div class="card">${flowHtml.join("\n")}</div>`;
}

// ─── Blast Radius Explorer ───────────────────────────────────────────────────

function renderBlastRadius(pkg: StructuredAnalysis["packages"][0]): string {
  const importEdges = pkg.importChain ?? [];
  if (importEdges.length === 0) return "";

  // Collect all files that are sources (can be explored)
  const sourceFiles = new Set<string>();
  for (const e of importEdges) sourceFiles.add(e.source);
  const sorted = [...sourceFiles].sort();

  return `
  <h2>Blast Radius Explorer</h2>
  <p style="color:var(--muted);font-size:0.9rem;margin-bottom:1rem">Select a file to see what depends on it &mdash; importers, co-change partners, and cluster membership.</p>
  <div class="card">
    <select id="blast-select" onchange="showBlast(this.value)">
      <option value="">Select a file...</option>
      ${sorted.map((f) => `<option value="${esc(f)}">${esc(shortPath(f))}</option>`).join("\n      ")}
    </select>
    <div id="blast-results" class="blast-results"></div>
  </div>`;
}

function renderBlastRadiusScript(pkg: StructuredAnalysis["packages"][0]): string {
  const importEdges = pkg.importChain ?? [];
  const coChangeEdges = pkg.gitHistory?.coChangeEdges ?? [];
  const clusters = pkg.coChangeClusters ?? [];

  // Serialize minimal data for client-side JS
  const importData = importEdges.map((e) => [e.source, e.importer, e.symbolCount] as const);
  const coChangeData = coChangeEdges.map((e) => [e.file1, e.file2, Math.round(e.jaccard * 100)] as const);

  return `<script>
const imports = ${JSON.stringify(importData)};
const cochanges = ${JSON.stringify(coChangeData)};
const clusters = ${JSON.stringify(clusters)};

function showBlast(file) {
  const el = document.getElementById('blast-results');
  if (!file) { el.innerHTML = ''; return; }

  const importers = imports.filter(e => e[0] === file).map(e => \`<li><code>\${e[1]}</code> <span class="badge badge-import">\${e[2]} symbols</span></li>\`);
  const cochangePartners = cochanges.filter(e => e[0] === file || e[1] === file).map(e => {
    const partner = e[0] === file ? e[1] : e[0];
    return \`<li><code>\${partner}</code> <span class="badge badge-cochange">\${e[2]}% co-change</span></li>\`;
  });
  const fileClusters = clusters.filter(c => c.includes(file)).map(c =>
    \`<li>\${c.length}-file cluster: \${c.filter(f => f !== file).map(f => \`<code>\${f}</code>\`).join(', ')}</li>\`
  );

  let html = '';
  if (importers.length > 0) html += \`<div class="blast-section"><h4>Importers (\${importers.length})</h4><ul>\${importers.join('')}</ul></div>\`;
  if (cochangePartners.length > 0) html += \`<div class="blast-section"><h4>Co-Change Partners</h4><ul>\${cochangePartners.join('')}</ul></div>\`;
  if (fileClusters.length > 0) html += \`<div class="blast-section"><h4>Cluster Membership</h4><ul>\${fileClusters.join('')}</ul></div>\`;
  if (!html) html = '<p class="empty">No dependencies found for this file.</p>';
  el.innerHTML = html;
}
</script>`;
}

// ─── Conventions ─────────────────────────────────────────────────────────────

function renderConventions(pkg: StructuredAnalysis["packages"][0]): string {
  const conventions = pkg.conventions ?? [];
  const antiPatterns = pkg.antiPatterns ?? [];

  if (conventions.length === 0 && antiPatterns.length === 0) return "";

  const items = [
    ...conventions.map(
      (c) =>
        `<div class="convention-item convention-do"><strong>DO:</strong> ${esc(c.name)} &mdash; ${esc(c.description)} <span class="badge" style="background:#dcfce7;color:#166534">${c.confidence.percentage}%</span></div>`,
    ),
    ...antiPatterns.map(
      (a) =>
        `<div class="convention-item convention-dont"><strong>DON'T:</strong> ${esc(a.rule)} &mdash; ${esc(a.reason)}</div>`,
    ),
  ];

  return `
  <h2>Conventions</h2>
  <div class="convention-list">${items.join("\n")}</div>`;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function fileDir(path: string): string {
  const idx = path.lastIndexOf("/");
  return idx >= 0 ? path.slice(0, idx) : ".";
}

function shortPath(path: string): string {
  // Shorten long paths: src/detectors/file-naming.ts → detectors/file-naming.ts
  const parts = path.split("/");
  return parts.length > 2 ? parts.slice(-2).join("/") : path;
}

function mermaidId(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_");
}
